title: "AWS Secure 3-Tier Architecture Docs"
description: "Comprehensive technical documentation for deploying a secure, resilient, Multi-AZ 3-Tier Web Architecture on AWS with WAFv2 and Graviton instances."
show_downloads: false
google_analytics:

# Include files starting with a dot
include: [".well-known"]

# Navigation settings
navbar:
  - title: "Home"
    url: "/"
  - title: "Architecture"
    url: "/engineering/architecture.html"
  - title: "Roadmap"
    url: "/executive/aws-adoption-roadmap.html"
  - title: "AI Handshake"
    url: "/engineering/ragflow-langfuse.html"
  - title: "Costing"
    url: "/executive/costing.html"
  - title: "Production Costing"
    url: "/executive/production-costing.html"
  - title: "Route 53"
    url: "/engineering/route53.html"
  - title: "Secure Access"
    url: "/engineering/jumphost.html"
  - title: "GitLab EFS CI/CD"
    url: "/engineering/gitlab-efs-cicd.html"
  - title: "Disaster Recovery"
    url: "/executive/dr-options.html"
  - title: "DR Evaluation"
    url: "/executive/dr-options-evaluation.html"
  - title: "RDS vs Percona"
    url: "/engineering/postgresql-comparison.html"
