title: "AWS Secure 3-Tier Architecture Docs"
description: "Comprehensive technical documentation for deploying a secure, resilient, Multi-AZ 3-Tier Web Architecture on AWS with WAFv2 and Graviton instances."
show_downloads: false
google_analytics:

# Include files starting with a dot
include: [".well-known"]

# Navigation settings
navbar:
  - title: "Home"
    url: "/"
  - title: "Architecture"
    url: "/architecture.html"
  - title: "Root Files"
    url: "/root-files.html"
  - title: "Scripts"
    url: "/scripts.html"
  - title: "CI/CD Pipeline"
    url: "/cicd.html"
  - title: "Costing"
    url: "/costing.html"
  - title: "Production Costing"
    url: "/production-costing.html"
  - title: "Route 53"
    url: "/route53.html"
  - title: "Secure Access"
    url: "/jumphost.html"
  - title: "GitLab EFS CI/CD"
    url: "/gitlab-efs-cicd.html"
  - title: "Disaster Recovery"
    url: "/dr-options.html"
  - title: "RDS vs Percona"
    url: "/postgresql-comparison.html"
