name: Generate Page PDF

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Webpage to PDF
        uses: misaelnieto/web_to_pdf_action@v0.3.1
        with:
          webPageURL: 'https://linuxmalaysia.github.io/aws-3tier-deployment-for-php-infra/'
          outputFile: './docs/assets/output.pdf'
          usePuppeteer: true
          pdfOptions: '{"format": "A4", "printBackground": true}'

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: page-pdf
          path: ./docs/assets/output.pdf
